-- MySQL Script generated by MySQL Workbench
-- Fri Dec 28 14:32:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ogsql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ogsql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ogsql` DEFAULT CHARACTER SET utf8 ;
USE `ogsql` ;

-- -----------------------------------------------------
-- Table `ogsql`.`POSTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`POSTS` (
  `ID` INT(9) NOT NULL,
  `TITULO` VARCHAR(150) NOT NULL,
  `SUBTITULO` VARCHAR(300) NULL,
  `TEXTO` VARCHAR(20000) NULL,
  `IDVOTOS` INT(9) NULL,
  `DATA` DATE NULL,
  `CATEGORIA` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogsql`.`IMG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`IMG` (
  `ID` INT(9) NOT NULL,
  `IDPOSTS` INT(9) NOT NULL,
  `NOME` VARCHAR(50) NOT NULL,
  `ARQUIVO` LONGBLOB NULL,
  `ORDEM` INT(9) NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDPOSTS_idx` (`IDPOSTS` ASC) VISIBLE,
  CONSTRAINT `IMGIDPOSTS`
    FOREIGN KEY (`IDPOSTS`)
    REFERENCES `ogsql`.`POSTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogsql`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`USUARIOS` (
  `ID` INT(9) NOT NULL,
  `NOME` VARCHAR(50) NULL,
  `SOBRENOME` VARCHAR(100) NULL,
  `EMAIL` VARCHAR(150) NULL,
  `CPF` VARCHAR(14) NULL,
  `SENHA` VARCHAR(45) NULL,
  `TIPO` CHAR(1) NULL,
  `GENERO` CHAR(1) NULL,
  `DTNASC` DATE NULL,
  `DTCAD` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogsql`.`COMMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`COMMENTS` (
  `ID` INT(9) NOT NULL,
  `IDPOSTS` INT(9) NOT NULL,
  `IDUSER` INT(9) NULL,
  `TEXTO` VARCHAR(500) NULL,
  `EMAIL` VARCHAR(100) NULL,
  `VOTOS` INT(9) NULL,
  `DATA` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `IDPOSTS_idx` (`IDPOSTS` ASC) VISIBLE,
  INDEX `USER_idx` (`IDUSER` ASC) VISIBLE,
  CONSTRAINT `COMPOSTS`
    FOREIGN KEY (`IDPOSTS`)
    REFERENCES `ogsql`.`POSTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `COMUSER`
    FOREIGN KEY (`IDUSER`)
    REFERENCES `ogsql`.`USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogsql`.`VOTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`VOTOS` (
  `ID` INT(9) NOT NULL,
  `IDPOSTS` INT(9) NULL,
  `IDUSER` INT(9) NULL,
  `IDCOMMENT` INT(9) NULL,
  `DATA` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `USER_idx` (`IDUSER` ASC) VISIBLE,
  INDEX `POSTS_idx` (`IDPOSTS` ASC) VISIBLE,
  INDEX `COMMENT_idx` (`IDCOMMENT` ASC) VISIBLE,
  CONSTRAINT `VOTOSUSER`
    FOREIGN KEY (`IDUSER`)
    REFERENCES `ogsql`.`USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VOTOSPOSTS`
    FOREIGN KEY (`IDPOSTS`)
    REFERENCES `ogsql`.`POSTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VOTOSCOMMENT`
    FOREIGN KEY (`IDCOMMENT`)
    REFERENCES `ogsql`.`COMMENTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogsql`.`ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`ADMIN` (
  `ID` INT(9) NOT NULL,
  `NOME` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogsql`.`PROTOCOLO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`PROTOCOLO` (
  `ID` INT(9) NOT NULL,
  `IDADMIN` INT(9) NULL,
  `IDUSER` INT(9) NULL,
  `EMAIL` VARCHAR(100) NULL,
  `DATA_INI` DATETIME NULL,
  `DATA_FIM` DATETIME NULL,
  `STATUS` CHAR(1) NULL,
  `PONTOS` INT(3) NULL,
  PRIMARY KEY (`ID`),
  INDEX `ADMIN_idx` (`IDADMIN` ASC) VISIBLE,
  INDEX `USUARIOS_idx` (`IDUSER` ASC) VISIBLE,
  CONSTRAINT `PROTADMIN`
    FOREIGN KEY (`IDADMIN`)
    REFERENCES `ogsql`.`ADMIN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROTUSUARIOS`
    FOREIGN KEY (`IDUSER`)
    REFERENCES `ogsql`.`USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogsql`.`CHAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`CHAT` (
  `ID` INT(9) NOT NULL,
  `IDPROT` INT(9) NULL,
  `REMETENTE` INT(9) NULL,
  `DEST` DATETIME NULL,
  `MSG` VARCHAR(200) NULL,
  `DATA` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `PROT_idx` (`IDPROT` ASC) VISIBLE,
  CONSTRAINT `CHATPROT`
    FOREIGN KEY (`IDPROT`)
    REFERENCES `ogsql`.`PROTOCOLO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogsql`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`PRODUTOS` (
  `ID` INT(9) NOT NULL,
  `TIPO` VARCHAR(50) NULL,
  `GENERO` VARCHAR(50) NULL,
  `FREE` CHAR(1) NULL,
  `PRECO` DOUBLE(7,2) NULL,
  `ARQUIVO` VARCHAR(500) NULL,
  `DATA` DATE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ogsql`.`ADQUIRIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ogsql`.`ADQUIRIDOS` (
  `ID` INT(9) NOT NULL,
  `IDUSER` INT(9) NULL,
  `IDPRODUTO` INT(9) NULL,
  `DATA` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `USUARIO_idx` (`IDUSER` ASC) VISIBLE,
  INDEX `PRODUTO_idx` (`IDPRODUTO` ASC) VISIBLE,
  CONSTRAINT `ADQUSUARIO`
    FOREIGN KEY (`IDUSER`)
    REFERENCES `ogsql`.`USUARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ADQPRODUTO`
    FOREIGN KEY (`IDPRODUTO`)
    REFERENCES `ogsql`.`PRODUTOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
